// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProSolutionFormsAPI.Data;

#nullable disable

namespace ProSolutionFormsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241118173021_Add UniqueReference Table")]
    partial class AddUniqueReferenceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProSolutionFormsAPI.Models.StudentUniqueReference", b =>
                {
                    b.Property<Guid>("StudentUniqueReferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentRef")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("StudentUniqueReferenceID");

                    b.HasIndex("StudentRef")
                        .IsUnique();

                    b.ToTable("StudentUniqueReference");
                });
#pragma warning restore 612, 618
        }
    }
}
